### ISSUE TITLE
Launching Ptyxis (Failed)

### ISSUE THREAD

**Issue by MLSci** [NiHaiden/aurora#15]
### Describe the bug

Can't open Ptyxis. When using GUI to open it, it shows an error msg: `Could not activate remote peer: unit failed.`

### What did you expect to happen?

Ptyxis starting normally.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 2h 13min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/nihaiden/aurora-dx-nvidia:latest
                   Digest: sha256:1e4ec8cfe1050393fdd1871788ed281395aebabde15510cb29a8eb9a4f755507
                  Version: 39.20240329.0 (2024-03-29T16:55:19Z)

  ostree-image-signed:docker://ghcr.io/nihaiden/aurora-dx-nvidia:latest
                   Digest: sha256:d8e99bc783461b9f8d89e34e53dcc03680c8308b15728775f18cbf3ba4fa2763
                  Version: 39.20240326.0 (2024-03-26T16:56:12Z)
```

### Extra information or context

May be related to this issue - https://universal-blue.discourse.group/t/system-unstable-after-flatpak-removal/932?u=oryarcul
You can ignore this bug if their fix applies to the upstream.

**Comment by NiHaiden** [comment]
Hi, sorry for the late response. Could you please try to update to the latest image and try opening Ptyxis again? I did a lot of changes today and it should work now.

**Comment by MLSci** [comment]
> Hi, sorry for the late response. Could you please try to update to the latest image and try opening Ptyxis again? I did a lot of changes today and it should work now.

What's the best way to update to the latest image? Reinstall the whole OS or .. ? (sorry I'm a noob)

Overall everything works pretty well. Good job!

**Comment by NiHaiden** [comment]
Just type `rpm-ostree update` in your terminal. That will pull the latest image from GitHub and install. This can take a while and there’s no progress bar, so let it run through. It will say to reboot when it’s done. 
thanks!

**Comment by NiHaiden** [comment]
Closing as this is resolved.
